### ISSUE TITLE
Gixtapsoe cubic example not working

### ISSUE THREAD

**Issue by chrisjonesBSU** [cmelab/GIXStapose#16]
I just created the environment and installed Gixtapose on Linux and tried running the cubic example and get the following error:

```
No input provided, showing simple cubic example
Traceback (most recent call last):
  File "/home/chris/miniconda3/envs/gixstapose/bin/gixstapose", line 33, in <module>
    sys.exit(load_entry_point('gixstapose', 'console_scripts', 'gixstapose')())
  File "/home/chris/cme/repos/GIXStapose/gixstapose/main.py", line 271, in main
    app = ApplicationWindow(args.input, args.frame)
  File "/home/chris/cme/repos/GIXStapose/gixstapose/main.py", line 50, in __init__
    self.initUI()
  File "/home/chris/cme/repos/GIXStapose/gixstapose/main.py", line 80, in initUI
    self.createGridLayout()
  File "/home/chris/cme/repos/GIXStapose/gixstapose/main.py", line 104, in createGridLayout
    toplayout.addWidget(dynamic_canvas, 0, 1)
TypeError: 'PySide2.QtWidgets.QGridLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QGridLayout.addWidget(FigureCanvasQTAgg, int, int)
Supported signatures:
  PySide2.QtWidgets.QGridLayout.addWidget(PySide2.QtWidgets.QWidget, int, int, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QGridLayout.addWidget(PySide2.QtWidgets.QWidget, int, int, int, int, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QGridLayout.addWidget(PySide2.QtWidgets.QWidget)
```

**Comment by jennyfothergill** [comment]
I have a feeling this is due to a problem between PyQt5 and PySide2. try running `conda uninstall pyqt5` or `pip uninstall pyqt5`. The _really_ pesky thing about this is it might break the interactive qt widgets in jupyter now even though they're in different environments. 🙃

**Comment by chrisjonesBSU** [comment]
That fixed it.
