### ISSUE TITLE
Cubic example not working

### ISSUE THREAD

**Issue by chrisjonesBSU** [cmelab/GIXStapose#22]
Looks like an issue with breaking changes in Pyside2? I tried it with both versions `5.13.21 and `5.15.8` which is the latest version. 

```
(gixstapose) ~ ❯ gixstapose
/home/chris/miniconda3/envs/gixstapose/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/chris/miniconda3/envs/gixstapose/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/chris/miniconda3/envs/gixstapose/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
No input provided, showing simple cubic example
Traceback (most recent call last):
  File "/home/chris/miniconda3/envs/gixstapose/bin/gixstapose", line 33, in <module>
    sys.exit(load_entry_point('gixstapose', 'console_scripts', 'gixstapose')())
  File "/home/chris/cme/forks/GIXStapose/gixstapose/main.py", line 271, in main
    app = ApplicationWindow(args.input, args.frame)
  File "/home/chris/cme/forks/GIXStapose/gixstapose/main.py", line 50, in __init__
    self.initUI()
  File "/home/chris/cme/forks/GIXStapose/gixstapose/main.py", line 80, in initUI
    self.createGridLayout()
  File "/home/chris/cme/forks/GIXStapose/gixstapose/main.py", line 104, in createGridLayout
    toplayout.addWidget(dynamic_canvas, 0, 1)
TypeError: 'PySide2.QtWidgets.QGridLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QGridLayout.addWidget(FigureCanvasQTAgg, int, int)
Supported signatures:
  PySide2.QtWidgets.QGridLayout.addWidget(PySide2.QtWidgets.QWidget, int, int, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QGridLayout.addWidget(PySide2.QtWidgets.QWidget, int, int, int, int, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QGridLayout.addWidget(PySide2.QtWidgets.QWidget)
```

Specifically this part:
```
TypeError: 'PySide2.QtWidgets.QGridLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QGridLayout.addWidget(FigureCanvasQTAgg, int, int)
```
We are trying to use `from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas` passed into `addWiget` but I guess it doesn't like that?

**Comment by chrisjonesBSU** [comment]
Nvm, this is the same as #16, uninstalling pyqt fixes it.
